name: Deploy to GitHub Pages
on:
  workflow_dispatch:  # 设置为手动触发
    inputs:
      artifact_name:
        description: 'Name of the Artifact to download (e.g., openwrt-bin-YYYY.MM.DD.HH.MM)'
        required: true
        type: string
        default: 'lede-bin-x86-64-2025.04.27.23.07'
jobs:
  Deploy:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Clean Up Disk Space
      run: |
        sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc || true
        sudo rm -rf /tmp/* /var/cache/* || true
        df -hT
    - name: Download Build Output Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: ./bin
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    - name: Check Downloaded Files
      run: |
        ls -la ./bin
        df -hT
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        publish_dir: ./bin
        publish_branch: gh-pages
        destination_dir: releases/23.05
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: 'Update OpenWrt repository files - ${{ github.event.workflow_run.head_commit.message }}'
        exclude_assets: '*.tar.xz, *.img.gz, *.tar.gz, *.zip'
    - name: Notify on Deploy Status
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        message: |
          发布状态 ${{ job.status }}!
          工作流: ${{ github.workflow }}
          用户名: ${{ github.actor }}
          仓库: ${{ github.repository }}
          软件源已发布到 GitHub Pages！
