name: make OpenWrt X86_64 deploy pages

on:
  workflow_dispatch:

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: configs/x86_64.config
  DIY_SCRIPT: diy-script.sh
  CLASH_KERNEL: amd64
  CACHE_TOOLCHAIN: true
  UPLOAD_BIN_DIR: false
  FIRMWARE_RELEASE: true
  FIRMWARE_TAG: X86_64
  TZ: Asia/Shanghai

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  Build:
    environment:
      name: github-pages
    runs-on: ubuntu-22.04

    steps:
      - name: Check Server Performance
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPU核心数量: $(nproc)"
          echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息:"
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android $AGENT_TOOLSDIRECTORY
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y update
          sudo -E apt-get -y install $(curl -fsSL https://raw.githubusercontent.com/tonylee2022/openwrt_d/main/depends_ubuntu_2204.txt)
          sudo -E systemctl daemon-reload
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get -y clean
          sudo timedatectl set-timezone "$TZ"

      - name: Combine Disks
        uses: easimon/maximize-build-space@master
        with:
          swap-size-mb: 1024
          temp-reserve-mb: 100
          root-reserve-mb: 1024

      - name: Checkout
        uses: actions/checkout@main

      - name: Clone Source Code
        run: |
          df -hT $GITHUB_WORKSPACE
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          cd openwrt
          # git checkout 9a4a9252051253a5a0271ecd41d95d3830c33305  ##修改lede版本
          echo "OPENWRT_PATH=$PWD" >> $GITHUB_ENV
          COMMIT_AUTHOR=$(git show -s --date=short --format="作者: %an")
          echo "COMMIT_AUTHOR=$COMMIT_AUTHOR" >> $GITHUB_ENV
          COMMIT_DATE=$(git show -s --date=short --format="时间: %ci")
          echo "COMMIT_DATE=$COMMIT_DATE" >> $GITHUB_ENV
          COMMIT_MESSAGE=$(git show -s --date=short --format="内容: %s")
          echo "COMMIT_MESSAGE=$COMMIT_MESSAGE" >> $GITHUB_ENV
          COMMIT_HASH=$(git show -s --date=short --format="hash: %H")
          echo "COMMIT_HASH=$COMMIT_HASH" >> $GITHUB_ENV

      - name: Generate Variables
        run: |
          cp $CONFIG_FILE $OPENWRT_PATH/.config
          cd $OPENWRT_PATH
          make defconfig > /dev/null 2>&1
          SOURCE_REPO="$(echo $REPO_URL | awk -F '/' '{print $(NF)}')"
          echo "SOURCE_REPO=$SOURCE_REPO" >> $GITHUB_ENV
          DEVICE_TARGET=$(cat .config | grep CONFIG_TARGET_BOARD | awk -F '"' '{print $2}')
          echo "DEVICE_TARGET=$DEVICE_TARGET" >> $GITHUB_ENV
          DEVICE_SUBTARGET=$(cat .config | grep CONFIG_TARGET_SUBTARGET | awk -F '"' '{print $2}')
          echo "DEVICE_SUBTARGET=$DEVICE_SUBTARGET" >> $GITHUB_ENV
          DEFAULT_VERSION=$(awk '/VERSION_NUMBER:=\$\(if/{gsub(/.*,/,""); gsub(/\).*/,""); print}' "./include/version.mk")
          echo "DEFAULT_VERSION=$DEFAULT_VERSION" >> $GITHUB_ENV

      - name: Cache Toolchain
        if: env.CACHE_TOOLCHAIN == 'true'
        uses: HiGarfield/cachewrtbuild@main
        with:
          ccache: false
          mixkey: ${{ env.SOURCE_REPO }}-${{ env.REPO_BRANCH }}-${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
          prefix: ${{ env.OPENWRT_PATH }}

      - name: Install Feeds
        run: |
          cd $OPENWRT_PATH
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Load Custom Configuration
        run: |
          [ -e files ] && mv files $OPENWRT_PATH/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE $OPENWRT_PATH/.config
          chmod +x $GITHUB_WORKSPACE/scripts/*.sh
          chmod +x $DIY_SCRIPT
          cd $OPENWRT_PATH
          $GITHUB_WORKSPACE/$DIY_SCRIPT
          # $GITHUB_WORKSPACE/scripts/preset-clash-core.sh $CLASH_KERNEL
          $GITHUB_WORKSPACE/scripts/preset-terminal-tools.sh
          # $GITHUB_WORKSPACE/scripts/preset-adguard-core.sh $CLASH_KERNEL

      - name: Download DL Package
        run: |
          cd $OPENWRT_PATH
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile Firmware
        id: compile
        run: |
          cd $OPENWRT_PATH
          mkdir -p files/etc/uci-defaults
          cp $GITHUB_WORKSPACE/scripts/init-settings.sh files/etc/uci-defaults/99-init-settings
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "DATE=$(date +"%Y-%m-%d %H-%M")" >> $GITHUB_ENV
          echo "FILE_DATE=$(date +"%Y.%m.%d.%H.%M")" >> $GITHUB_ENV

      - name: Check Space Usage
        if: (!cancelled())
        run: df -hT

      - name: Upload Bin Directory
        if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: lede${{ env.DEFAULT_VERSION }}-bin
          path: |
            ${{ env.OPENWRT_PATH }}/bin/packages/
            ${{ env.OPENWRT_PATH }}/bin/targets/x86/64/packages/

      - name: Organize Files
        if: steps.compile.outputs.status == 'success'
        run: |
          cd $OPENWRT_PATH/bin/targets/*/*
          cat sha256sums
          cp $OPENWRT_PATH/.config build.config
          rm -rf feeds.buildinfo version.buildinfo
          echo "KERNEL=$(cat *.manifest | grep ^kernel | cut -d- -f2 | tr -d ' ')" >> $GITHUB_ENV
          export FIRMWARE_PATH=$PWD  # 立即在当前 Shell 中生效
          echo "FIRMWARE_PATH=$FIRMWARE_PATH" >> $GITHUB_ENV  # 写入后续步骤环境变量
          mkdir -p $OPENWRT_PATH/temp-packages
          cp $OPENWRT_PATH/bin/packages/*/*/*.ipk $OPENWRT_PATH/temp-packages/ || true
          cp $OPENWRT_PATH/bin/targets/*/*/*/*.ipk $OPENWRT_PATH/temp-packages/ || true
          tar -zcf "$FIRMWARE_PATH/Packages.tar.gz" "$OPENWRT_PATH/temp-packages"  # 使用双引号避免路径空格问题
          rm -rf $OPENWRT_PATH/temp-packages

      - name: Upload Firmware To Release
        if: steps.compile.outputs.status == 'success' && env.FIRMWARE_RELEASE == 'true'
        uses: ncipollo/release-action@v1
        with:
          name: R${{ env.FILE_DATE }} for ${{ env.FIRMWARE_TAG }}
          allowUpdates: true
          tag: ${{ env.FILE_DATE }}
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: ${{ env.FIRMWARE_PATH }}/*
          body: |
            **This is OpenWrt Firmware for ${{ env.FIRMWARE_TAG }}**
            ### 📒 固件信息
            - 💻 平台架构: ${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
            - ⚽ 固件源码: ${{ env.REPO_URL }}
            - 💝 源码分支: ${{ env.REPO_BRANCH }} ${{ env.DEFAULT_VERSION }}
            - 🚀 内核版本: ${{ env.KERNEL }}
            - 🌐 默认地址: 192.168.5.1
            - 🔑 默认密码: password
            ### 🧊 固件版本
            - 固件编译前最后一次➦[主源码](${{ env.REPO_URL }})更新记录
            - ${{ env.COMMIT_AUTHOR }}
            - ${{ env.COMMIT_DATE }}
            - ${{ env.COMMIT_MESSAGE }}
            - ${{ env.COMMIT_HASH }}

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@master
        if: env.FIRMWARE_RELEASE == 'true' && !cancelled()
        with:
          keep_latest: 6
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify on Compile Status
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            编译状态 ${{ job.status }}!
            工作流: ${{ github.workflow }}
            用户名: ${{ github.actor }}
            仓库: ${{ github.repository }}
            固件源码: ${{ env.REPO_URL }}
            源码分支: ${{ env.REPO_BRANCH }} ${{ env.DEFAULT_VERSION }}
            Commit: ${{ github.sha }}
            等待GitHub Pages软件源发布

      - name: Prepare directory structure
        run: |
          cd $FIRMWARE_PATH   
          # 删除指定后缀名的文件
          echo "删除指定后缀名的文件..."
          find "$FIRMWARE_PATH" -type f \( -name "*.bin" -o -name "*.img" -o -name "*.img.gz" -o -name "*.tar.gz" -o -name "*.tar.xz" \) -exec rm -v {} + || echo "删除特定后缀文件可能失败，请检查日志"  
          # 列出大于100MB的文件
          echo "列出大于100MB的文件..."
          find "$FIRMWARE_PATH" -type f -size +100M -ls    
          # 删除大于100MB的文件
          echo "删除大于100MB的文件..."
          find "$FIRMWARE_PATH" -type f -size +100M -exec rm -v {} + || echo "删除大文件操作可能失败，请检查日志"    
          echo "清理完成"
          # 切换到OPENWRT路径
          cd "$OPENWRT_PATH" || { echo "错误: 无法进入 $OPENWRT_PATH 目录"; exit 1; }
          # 创建目录结构
          mkdir -p "./pages/releases/$DEFAULT_VERSION"
          # 检查bin目录并移动文件
          if [ -d "./bin" ] && [ "$(ls -A ./bin 2>/dev/null)" ]; then
            echo "移动文件从 ./bin/ 到 ./pages/releases/$DEFAULT_VERSION/"
            mv ./bin/* "./pages/releases/$DEFAULT_VERSION/" || echo "移动文件过程中出现错误"
          else
            echo "警告: bin目录不存在或为空，没有文件可移动"
          fi
          # 设置PAGES_PATH环境变量
          cd "./pages" || { echo "错误: 无法进入 pages 目录"; exit 1; }
          export PAGES_PATH=$PWD
          echo "设置PAGES_PATH=$PAGES_PATH"
          echo "PAGES_PATH=$PAGES_PATH" >> $GITHUB_ENV
          # 显示目录结构
          echo "当前 pages 目录结构："
          tree "$PAGES_PATH" || ls -R "$PAGES_PATH"

      - name: Generate recursive index.html
        run: |
          #!/usr/bin/env bash
          set -e
          cd $PAGES_PATH
          find . -type d | while read dir; do
            cd "$dir"
            title_name=$(basename "$PWD")
            echo '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>'"$title_name"'</title></head><body><h1>Index of /'"$dir"'</h1><hr><pre><a href="../index.html">../</a>' > index.html
            for f in *; do
              [ "$f" != "index.html" ] && \
              if [ -d "$f" ]; then
                # 对于目录，链接长度与文件名长度一致
                printf '<a href="%s/index.html">%s/</a>                                                  -\n' "$f" "$f" >> index.html
              else
                size=$(stat -c %s "$f")
                mod_time=$(stat -c %y "$f" | cut -d' ' -f1 | cut -d'-' -f1-2 | tr '-' '/')$(stat -c %y "$f" | cut -d' ' -f2 | cut -d':' -f1-2)
                # 计算文件名长度
                f_len=${#f}
                # 如果文件名长度超过50，截断并用>表示
                if [ $f_len -gt 50 ]; then
                  f_display=${f:0:49}'>'
                  padding=''
                else
                  f_display=$f
                  # 计算需要填充的空格数
                  padding=$(printf '%*s' $((50 - f_len)) '')
                fi
                # 打印文件信息，确保日期列对齐
                printf '<a href="%s">%s</a>%s %-15s %15d\n' "$f" "$f_display" "$padding" "$mod_time" "$size" >> index.html
              fi
            done
            echo '</pre><hr></body></html>' >> index.html
            cd - >/dev/null
          done
          # 显示目录结构
          echo "当前 pages 目录结构："
          tree "$PAGES_PATH" || ls -R "$PAGES_PATH"

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PAGES_PATH }}

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Notify Deploy Status
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            🚀 OpenWrt 软件源发布完成！
            状态: ${{ job.status }}
            仓库: ${{ github.repository }}
            版本: ${{ env.DEFAULT_VERSION }}
            架构: ${{ env.DEVICE_TARGET }}-${{ env.DEVICE_SUBTARGET }}
            Pages 地址: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/releases/${{ env.DEFAULT_VERSION }}/
